# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10n6tUzr5_6LntIxU6fwu_jSIDEChOxnz

Ejemplo de hash Ripmed-160
"""

import hashlib

nombre_archivo = "resources/diez.txt"  # Nombre del archivo de texto que deseas leer

with open(nombre_archivo, "r") as archivo:
    contenido = archivo.read()
    

valor_hash = hashlib.new("ripemd160", contenido.encode()).hexdigest()
print(valor_hash)




nombre_archivo = "cien.txt"  # Nombre del archivo de texto que deseas leer

with open(nombre_archivo, "r") as archivo:
    contenido = archivo.read()
    
valor_hash = hashlib.new("ripemd160", contenido.encode()).hexdigest()
print(valor_hash)



nombre_archivo = "mil.txt"  # Nombre del archivo de texto que deseas leer

with open(nombre_archivo, "r") as archivo:
    contenido = archivo.read()
    
valor_hash = hashlib.new("ripemd160", contenido.encode()).hexdigest()
print(valor_hash)



nombre_archivo = "diez_mil.txt"  # Nombre del archivo de texto que deseas leer

with open(nombre_archivo, "r") as archivo:
    contenido = archivo.read()
    
valor_hash = hashlib.new("ripemd160", contenido.encode()).hexdigest()
print(valor_hash)



nombre_archivo = "cien_mil.txt"  # Nombre del archivo de texto que deseas leer

with open(nombre_archivo, "r") as archivo:
    contenido = archivo.read()
    
valor_hash = hashlib.new("ripemd160", contenido.encode()).hexdigest()
print(valor_hash)



nombre_archivo = "millon.txt"  # Nombre del archivo de texto que deseas leer

with open(nombre_archivo, "r") as archivo:
    contenido = archivo.read()
    
valor_hash = hashlib.new("ripemd160", contenido.encode()).hexdigest()
print(valor_hash)